### PR TITLE
Import on local component

### PR DESCRIPTION
**Pull request by sadick254**
This will enable one to import it on local components where he/she might want to use it.
https://forum.vuejs.org/t/npm-install-use-local-component/22062/2

### CODE REVIEW

**Comment by BrockReece** [comment]
Hi, thanks for the PR.

So the proposed usage would be...

```js
// foo.vue
import {FullCalendar} from 'vue-full-calendar'
export {
  components: { FullCalendar },
  ...
}
```

is importing the component directly not working or bad practise?

```js
// foo.vue
import FullCalendar from 'vue-full-calendar/src/FullCalendar.vue'
export {
  components: { FullCalendar },
  ...
}
```

**Comment by sadick254** [comment]
It is working but it is not immediately obvious that someone should import it in this way
`import FullCalendar from 'vue-full-calendar/src/FullCalendar.vue`
I personaly think 
`import {FullCalendar} from 'vue-full-calendar'`
Is more straight forward when someone wants to use it in a local component

**Comment by BrockReece** [comment]
I agree that it looks neater but I think we would still need something in the readme as I don't believe this is any more obvious, unless this is common pattern that has completely passed me by?

**Comment by sadick254** [comment]
It is a common pattern in many vue components. And its true that we would need something in the readme.

**Comment by BrockReece** [comment]
Ok, thanks for this.

I have merged this in to a feature branch so I can add something to the readme and add some tests before merging it into master

Cheers
Brock

**Pull request merged**
